// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArHV--REe9tdOH1115khGcQvZuIutT_2k',
    appId: '1:348803098354:web:a6d73951fd713ee4f3926b',
    messagingSenderId: '348803098354',
    projectId: 'esp32-teste-a994f',
    authDomain: 'esp32-teste-a994f.firebaseapp.com',
    databaseURL: 'https://esp32-teste-a994f-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-teste-a994f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6FbsCF25aUt9zlZsW-x2Gr45PRihNb7w',
    appId: '1:348803098354:android:e75a61e252a7797ef3926b',
    messagingSenderId: '348803098354',
    projectId: 'esp32-teste-a994f',
    databaseURL: 'https://esp32-teste-a994f-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-teste-a994f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA16verqzJAJfwCa1cjAUNrrQlHdr9qJfU',
    appId: '1:348803098354:ios:3cb89f89419b6c95f3926b',
    messagingSenderId: '348803098354',
    projectId: 'esp32-teste-a994f',
    databaseURL: 'https://esp32-teste-a994f-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-teste-a994f.appspot.com',
    iosClientId: '348803098354-0dc09gpun13hu0qdpmv9q2qcmvquk6g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA16verqzJAJfwCa1cjAUNrrQlHdr9qJfU',
    appId: '1:348803098354:ios:3cb89f89419b6c95f3926b',
    messagingSenderId: '348803098354',
    projectId: 'esp32-teste-a994f',
    databaseURL: 'https://esp32-teste-a994f-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-teste-a994f.appspot.com',
    iosClientId: '348803098354-0dc09gpun13hu0qdpmv9q2qcmvquk6g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
